---
title: 'Predictive Analysis Project2 :'
author: Jered Ataky, Matthew Baker, Christopher Bloome, David Blumenstiel, Dhairav Chhatbar
date: "7/7/2021"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(dplyr)
library(readxl)
library(skimr)
library(tidyr)
library(kableExtra)
library(mice)
library(VIM)
library(corrplot)
library(ggcorrplot)
```


## Introduction
<insert intro text>

## Data Prepration
<insert data load text>
```{r, message=FALSE, warning=FALSE, message=FALSE}

train_dataset <- read.csv("https://raw.githubusercontent.com/jnataky/Predictive_Analytics/main/Project2/StudentData%20-%20TO%20MODEL.csv")
test_dataset <- read.csv("https://raw.githubusercontent.com/jnataky/Predictive_Analytics/main/Project2/StudentEvaluation-%20TO%20PREDICT.csv")

head(train_dataset)


```

## Explorative Data Analysis
<description/discussion of each visual>
```{r}
skim(train_dataset)
```
```{r, warning=FALSE}
aggr(train_dataset, col=c('#F8766D','#00BFC4'), numbers=TRUE, sortVars=TRUE, labels=names(train_dataset), cex.axis=.7, gap=3, ylab=c("Missing data","Pattern"))
```

```{r, warning=FALSE}
train_dataset %>% select(PH) %>% ggplot( aes(PH)) + geom_density(fill="steelblue", bins = 30)
```


```{r, fig.height=10, warning=FALSE, message=FALSE}

train_dataset %>% select(-PH, -Brand.Code) %>% 
  tidyr::gather(key = "variable", value = "measurement",everything()) %>% 
  arrange(desc(variable)) %>%
  ggplot(aes(measurement)) + geom_density(position=position_dodge(), fill="steelblue") +
  facet_wrap(~variable, scales = "free") +
  theme_minimal() + 
  ggtitle("Distribution of Predictor Variables")
```

```{r, fig.height=10}
q <- cor(train_dataset%>%select(-Brand.Code), use = "na.or.complete")
ggcorrplot(q, type = "lower", outline.color = "white", hc.order = TRUE,
           colors = c("#6D9EC1", "white", "#E46726"),
           lab = TRUE, show.legend = FALSE, tl.cex = 8, lab_size = 3) 



```



## Data Transformation
<text of any data transformation that was done>
```{r}

```


## Modeling
<text on which models are going to be used>

## Model Accuracy
<show/discuss accuracy of models>

### Model 1: <model name>
```{r}

```

### Model 2: <model name>
```{r}

```

### Model 3: <model name>
```{r}

```


## Forcasting & Conclusion
<text on the chosen model, forcasting, and conclusion>
```{r}

```



